### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Zachary-Harrison** [DLCIncluded/MQ#1]
I just noticed some typos and thought you might be interested in fixing them. Spell-checking is one of my special interests, so I hope this is helpful and not rude.

- The "_StronglyAgree_" option needs a space in it.
- One of the questions (close to the middle) is missing a space: "I have trouble filtering out sounds when I am not doing something I'm _focusedon_."

**Comment by DLCIncluded** [comment]
Thank you! I copied and pasted from the PDF and some of them didn't paste right. I thought I got all of them I'll get that fixed ASAP thanks!

**Comment by DLCIncluded** [comment]
Fixed typos, added the space in _Strongly Agree_ and _focused on_
Thanks again!
