### ISSUE TITLE
Add note on keyboard navigation to description

### ISSUE THREAD

**Issue by chris4727** [DLCIncluded/MQ#12]
The keyboard navigation for the quiz is incredible, but there is nothing in the description to tell users it exists. With so many online forms and questionnaires having terrible keyboard navigation, users who appreciate this feature may not try to use it.

I have included an example. Feel free to use this language if you find it helpful:

> **Keyboard navigation:**
> - Jump to the next or previous question using `Tab` or `Shift+Tab`.
> - Select your answer using the arrow keys.

Thank you for making this excellent application, keeping the data local, and for making it such a pleasure to use with the keyboard.

**Comment by DLCIncluded** [comment]
Hey, sorry for the delay, been busy!

Honestly, I didn't intentionally add keyboard navigation lol 

I can put a note however, thanks for the suggestion!

**Comment by DLCIncluded** [comment]
Deployed
