### ISSUE TITLE
Add helpful link (in case of high scores?)

### ISSUE THREAD

**Issue by oolong** [DLCIncluded/MQ#13]
I wrote a page for people who have just realised they're more monotropic than most: [I'm Monotropic, Now What?](https://monotropism.org/im-monotropic-now-what/)

I wonder if it could make sense to link people directly there when they get their results and it turns out they're more monotropic than, say, 90% of people?

Speaking of being more monotropic than x% of people, I've noticed quite a lot of people misreading this and thinking they're 60% more monotropic than autistic people. Which doesn't make much sense to me, and some misreadings are inevitable, but I wonder if there's a way to phrase this which might cause slightly less confusion! Any ideas?

**Comment by DLCIncluded** [comment]
Hey sorry for the delay - been busy!

Adding the link now

As for the x% of people question... hmm i see what you're saying, its hard to word that to be understandable to everyone

The only real thing we could do is try to add an explanation afterwards

**Comment by DLCIncluded** [comment]
The link is deployed, it displays if you have >=90% or >=3.91 avg
![image](https://github.com/DLCIncluded/MQ/assets/23517228/ca28365a-c3b8-4231-8034-22d8fda5fb1f)
![image](https://github.com/DLCIncluded/MQ/assets/23517228/845012be-07cb-43d4-a066-cef8c268a739)

**Comment by oolong** [comment]
Great, thank you!

I think maybe the phrasing issue is probably best resolved by a graphic display, so I'll close this for now.
