### ISSUE TITLE
Internationalisation/translations

### ISSUE THREAD

**Issue by oolong** [DLCIncluded/MQ#15]
How much work would it be to make this work in multiple languages? [Someone's translated the questions into Portuguese](https://docs.google.com/document/d/1fJiyadxffp7cYio4bMo-R1d7bZsCWlcs/edit?usp=sharing&ouid=115915902274775408822&rtpof=true&sd=true)!

**Comment by DLCIncluded** [comment]
Hey thats awesome! I should be able to implement that fairly easily, I'll work on that shortly

**Comment by DLCIncluded** [comment]
Build should be going out shortly with Portuguese translation added, thanks!
