### ISSUE TITLE
Request to number questions

### ISSUE THREAD

**Issue by ovalmachine** [DLCIncluded/MQ#16]
Just so that people know how far through they are!

**Comment by DLCIncluded** [comment]
As the original [Questionnaire](https://osf.io/4wru2) doesn't number them, I'm not sure if I will add this, I understand where you're coming from, but I want to keep it true to the original as best I can. Thank you for the suggestion, If I do add it I'll let you know!

**Comment by DLCIncluded** [comment]
Instead of numbering, added a simple progress indicator 
99a75f0
