### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by MQPLDE** [DLCIncluded/MQ#17]
Hi, I'm uploading German translation of the questions. I noticed you aren't asking for answers, so if you need also the translations of possible answers, feel free to ask! 
[questions DE.txt](https://github.com/DLCIncluded/MQ/files/14239391/questions.DE.txt)

**Comment by DLCIncluded** [comment]
Hey! Thanks :) good catch on the answers, I did forget to mention that, if you could do the answers for both and when I get a sec I'll get both your translations added

Thanks again!

**Comment by MQPLDE** [comment]
Happy to help! Uploading both translations of answers :)
[answers DE PL.txt](https://github.com/DLCIncluded/MQ/files/14257567/answers.DE.PL.txt)
