### ISSUE TITLE
German translation error

### ISSUE THREAD

**Issue by ff2000** [DLCIncluded/MQ#19]
The German translation translates "Agree" to "Stimme NICHT zu" (=Disagree), so you will get the opposite of your actual result.

**Comment by DLCIncluded** [comment]
Thank you, I will look into this ASAP

**Comment by nielbock** [comment]
> The German translation translates "Agree" to "Stimme NICHT zu" (=Disagree), so you will get the opposite of your actual result.

Yes, I just recognised it, too. The scale is reversed. The result didn't make any sense.

**Comment by DLCIncluded** [comment]
Apologies there, thanks for bringing it to my attention I'll work on getting it fixed, community members contribute to the translations

Ive been terribly busy at work, but I will get this fixed ASAP

**Comment by DLCIncluded** [comment]
New build should be going out with this fixed, please let me know if that fixed the issue
