### ISSUE TITLE
Russian translation UPD: please change the answers !!

### ISSUE THREAD

**Issue by rib3n4** [DLCIncluded/MQ#20]
Here is a translation into russian, answers and questions in order. 
[mono rus.txt](https://github.com/DLCIncluded/MQ/files/14735132/mono.rus.txt)

**Comment by DLCIncluded** [comment]
This should be deployed, please let me know if there is any issues with it, I confirmed with google translate that they match EN to RUS, but if I missed any or put them in the wrong order please let me know

**Comment by rib3n4** [comment]
looks allright, thanks!

**Comment by rib3n4** [comment]
uwu sorry it's me again, some of the people who took the test in russian told me that those double endings with slashes in answers don't look very good, so i'd like to change them to these gender-neutral forms. russian is so gendered meh
[mono rus answers2.txt](https://github.com/DLCIncluded/MQ/files/14808394/mono.rus.answers2.txt)

**Comment by DLCIncluded** [comment]
Deploying now, will be available in a few minutes
