### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by AlejMnoz** [DLCIncluded/MQ#21]
Hi! I translated the questionnaire to Spanish. 

[MQ Spanish.txt](https://github.com/DLCIncluded/MQ/files/15026171/MQ.Spanish.txt)

Answers, from "Strongly disagree" to "Strongly agree":

- N/A [Alternatively, you could simply put "No aplica"].
- Muy en desacuerdo.
- En desacuerdo.
- Ni de acuerdo ni en desacuerdo.
- De acuerdo.
- Muy de acuerdo.

Thank you for putting this test out there for everyone!

**Comment by DLCIncluded** [comment]
Thank you! Sorry for the delay, but I finally got time to add this. Please let me know if there are any issues!
