### ISSUE TITLE
Answers reversed in Polish translation

### ISSUE THREAD

**Issue by Bahiri9** [DLCIncluded/MQ#22]
Hello
I have noticed that answers in Polish are reversed in comparison to English. But they are only reversed visually, so a person with really high score in English get low score. In mine it was arond 63 in Polish, but 217 in English.

It is worth to mention that N/A option is okay.

![Screenshot_20240504-204654_Samsung Internet](https://github.com/DLCIncluded/MQ/assets/168931035/dd316599-96b9-44ef-ba8b-90b40e025eb1)
![Screenshot_20240504-204700_Samsung Internet](https://github.com/DLCIncluded/MQ/assets/168931035/90e02337-b434-4c22-b79a-21d02729d79d)

**Comment by DLCIncluded** [comment]
My apologies, thank you for pointing that out I will get it fixed ASAP!

**Comment by Bahiri9** [comment]
No problem, I have found it because I did some other tests like raadsr and had high score.

It was really fast answer, thanks ;)
Let me know if you will be in need to check it again, i can eagerly do it

**Comment by DLCIncluded** [comment]
Give it a few minutes, the new build should be up with the hopefully correct translations, but please let me know if there are any other issues! Thank you :)
