### ISSUE TITLE
improve visibility

### ISSUE THREAD

**Issue by parkermae** [DLCIncluded/MQ#23]
It is difficult for me to read the questions and answers due to formatting. Users with vision/sensory processing issues could benefit from the questions being a different color and/or size. Extra credit to make each answer it's own color (red N/A, orange Strongly Disagree, etc) or different shades of one color.
![2024-06-03 07_19_28-Mozilla Firefox](https://github.com/DLCIncluded/MQ/assets/171581869/1a1a9cad-3880-481a-84b8-a15020f6fc3e)

**Comment by DLCIncluded** [comment]
Hey, thanks for the feedback; As I struggle with colors, I will do my best

Could you give screenshots and descriptions of the formatting that is difficult to read? If I could better understand what is causing the issue, I can do my best to attempt to fix thanks!

**Comment by parkermae** [comment]
I have some trouble focusing on anything when it's all the same style. When I look at the questionnaire my vision becomes unfocused and I'm just staring at a wall of words. I'm happy to help zhuzh it up by taking your source code and adding style, colors of your choosing and uploading it as a text file here. I used to design CSS for website users to customize their profiles and group pages.
![2024-06-03 14_27_55-MQ Assessment](https://github.com/DLCIncluded/MQ/assets/171581869/cbe7ebe8-45b8-4d36-960b-7e583f18e260)

**Comment by DLCIncluded** [comment]
Thank you, will work on this when I can

**Comment by DLCIncluded** [comment]
Had some time tonight, take a look when you have a chance and let me know if that helps
- added color to the answers, along with a border
- increased text size for Question text

**Comment by parkermae** [comment]
That made a huge difference! Thank you for the added accessibility!
