### ISSUE TITLE
French translation for the MQ

### ISSUE THREAD

**Issue by Crowleyminal** [DLCIncluded/MQ#24]
Hello,
I wanted to contribute, so I translated the statements and answers for the MQ in French [Questions.txt](https://github.com/user-attachments/files/15596515/Questions.txt) [Answers.txt](https://github.com/user-attachments/files/15596591/Answers.txt).
Statements are in order as they are presented in the questions.txt file on GitHub

Note :

It's complicated to be gender neutral in French so I used the most common solution for this: adding the feminine suffix between parentheses. 
Also, statement line 41 was tricky. (I tend to feel quite self-conscious unless I’m deeply absorbed in a task.)
Self-conscious has no equivalent word in French so there will be a loss in translation here.
— J’ai tendance à me sentir assez mal à l’aise sauf lorsque je suis profondément absorbé par une tâche."
“J’ai tendance à me sentir assez gêné/mal à l’aise” would mean “I feel quite awkward/embarrassed/shy”, losing the “self-awareness” part of the word.
— J’ai tendance à ressentir un excès de “conscience de soi” sauf lorsque je suis profondément absorbé par une tâche.
“J’ai tendance à ressentir un excès de conscience de soi” would mean “I feel an excess in self-awareness”, losing the "awkward/embarrassed/shy" part of the word. “conscience de soi” (self-awareness) is not something negative but "excess" implies that there is something wrong about it being too much.

The first option is the most fluid in French, but there is a significant loss in translation.
I feel like the 2nd option is closer to the intended meaning but it might be seen as too much of a literal translation for some.

I put the 2nd option in the file, but feel free to change it if you think the 1st option is better.

**Comment by DLCIncluded** [comment]
Thank you, I will try to get this in as soon as possible

And thank you for the great explanation!

**Comment by DLCIncluded** [comment]
I think I'm going to add the second option, to stay closer to the intended, even though it may be a bit too literal, Hopefully it still gets the point across

If we get any complaints/opinions on it from someone else who speaks French and disagrees with that choice we can always change it later lol 

I had a second to get this added so it will be up shortly, within 5-10 min 

Thank you again! Also let me know if you see any issues

**Comment by acrostich** [comment]
@Crowleyminal 
> I feel like the 2nd option is closer to the intended meaning 

I agree with this. My French is very rusty but I'm wondering about the following alternative?

Je suis tres sensible au regard des autres sauf lorsque je suis profondément absorbé par une tâche.

**Comment by Crowleyminal** [comment]
@acrostich 

> Je suis très sensible au regard des autres sauf lorsque je suis profondément absorbé par une tâche.

It's a very good way to translate it!
There is still a small loss as you can feel self-conscious when you are alone, or not perceived by anyone.
However, it conveys the meaning of a subjective feeling based on perception and it is more natural than my proposition.

I think it is better, you are right.

**Comment by Crowleyminal** [comment]
There is also the option of the metaphor.

Je me sens comme un éléphant dans un magasin de porcelaine sauf lorsque je suis profondément absorbé par une tâche.
(I feel like an elephant in a China shop unless I’m deeply absorbed in a task.)

The meaning of this saying is to feel clumsy, but it conveys the idea of person feeling too self-aware in the wrong environment.
While the elephant not belonging inside the shop is not really subjective, it is nuanced by "I feel like".
However, it would stand out a bit regarding the other statements.

**Comment by acrostich** [comment]
I find the use of metaphors would make the question less accessible as not everyone is familiar and/or understands metaphors even though this one is a rather common one. Also it would imply that when absorbed in a task, one would feel unlike an elephant in a China shop which is much less clear.

**Comment by Crowleyminal** [comment]
I agree, it might make it less accessible and the tone of the rest of the questions is more neutral compared this metaphor.

**Comment by DLCIncluded** [comment]
Apologies for the delay! Work/life got really busy after this request
I like that last translation, you both had excellent points, so went ahead and added that one, appreciate your help! 
Going to close this out, if you notice any issues please let me know
