### ISSUE TITLE
Possibly add a little black dot at the tip of the arrow?

### ISSUE THREAD

**Issue by MilkWay3011** [DLCIncluded/MQ#25]
I'm a visually impaired person, and even with zooming and it is quite hard to tell where I could be so would be helpful if you would add a little black dot at the tip of the arrow! Thank you for possibly considering this request!

**Comment by DLCIncluded** [comment]
Hey! That's an awesome idea, thank you for the suggestion

I will take a look tomorrow and see what I can do to make it easier to see, I know that graph isn't perfect, it's really janky lol but I'll see what I can do!

**Comment by MilkWay3011** [comment]
Wow! I wasn't expecting you to get back so quickly! thanks for considering my suggestion!

**Comment by DLCIncluded** [comment]
Mobile:
![image](https://github.com/user-attachments/assets/2c79c414-68b9-4a53-86e5-5ab1fe60eaec)

Desktop:
![image](https://github.com/user-attachments/assets/2b804a22-eb89-4340-b366-910546d4a8c3)

Apologies for the delay there, had a busy week

Added a small black dot just above the arrow point, and a note about the chart, as it is just a visual representation of where the score falls in relation to the others, but thank you for the suggestion, and hope it helps! 

Will be on the site shortly
