### ISSUE TITLE
When Printing results, Purple Arrow on Graph is in incorrect position

### ISSUE THREAD

**Issue by rrmcmurry** [DLCIncluded/MQ#26]
I wanted to start by saying thanks for building out this awesome Monotropism quiz. I appreciate it.  I scored a 4.15, am Monotropic, and have been studying everything related to autism since realizing that I was autistic a few weeks ago.  I am 43, so this is a very late diagnosis... and every little bit helps me come to terms with it.  I've been printing the results of all of the online quizzes and diagnostics I've come across to a file for future reference and I found an error when I went to print my results after taking your quiz.

On screen, the purple arrow on the graph at the bottom of the page points to a dot that is roughly in the center of the autistic green dots at 4.15/5.  When I go to print the page, the purple arrow is all the way to the right margin of the page, not even on the graph.  I figure this is likely a CSS issue and I just wanted to make you aware of it.  I'm using Chrome version 127.0.6533.89. 

Thanks again!

**Comment by DLCIncluded** [comment]
Hey, thanks for reporting

Not entirely sure if I will be able to fix, as like you guessed its a CSS issue. The arrow is  placed using dynamic CSS positioning and is calculated on completion/calculation of score so I'm not entirely sure I will be able to fix, however, I will definitely take a look and see if it is possible!

**Comment by DLCIncluded** [comment]
With a bit of tweaking I believe I came up with a solution:
![image](https://github.com/user-attachments/assets/31be3dbd-479a-48a4-bc2d-3e5e3188083d)

Seems to be working better, just  doing a few more tests and will push it out

**Comment by DLCIncluded** [comment]
Deployed the update
Print Preview seems to show it staying the same place ( also changed it to blue, idk why i picked purple in the first place)

I don't have my printer available right now to properly test, but let me know if this fixes the issue!

**Comment by rrmcmurry** [comment]
I can confirm that this issue is fixed. Thanks!
