### ISSUE TITLE
answers outlook may interfere with results

### ISSUE THREAD

**Issue by bazyliquest** [DLCIncluded/MQ#27]
Every answer box should have the same size. People are more eager to click on bigger shapes thus it may influence answers.

Colors may influence answers as well (e.g. somebody may not like given color). I understand the idea of color-coding for faster association but unfortunately it may be a noise for many users.

To improve readability radiobuttons should be centered to labels.
![IMG_1041](https://github.com/user-attachments/assets/74195006-b6aa-4a37-9dc7-fdbc1a836beb)

**Comment by DLCIncluded** [comment]
What browser are you using? You're the first to mention the radio buttons
not being centered, and I've tested chrome, Firefox and mobile.

Mobile with "view as desktop" is first screen shot, mobile view is second.

**Comment by DLCIncluded** [comment]
![Screenshot_20240901_091555_Chrome.jpg](https://github.com/user-attachments/assets/eec4cfd7-dcbc-475b-868a-f5113f3ddc3f)

![Screenshot_20240901_091708_Chrome.jpg](https://github.com/user-attachments/assets/95b69cfe-5384-4200-bd1e-ac694da47fbe)

**Comment by DLCIncluded** [comment]
And this is on FF and Chrome on desktop:
![image](https://github.com/user-attachments/assets/a386e152-df3d-4ccb-ad5e-052b8552f015)
![image](https://github.com/user-attachments/assets/9b0c830f-b53c-493b-8ffb-3882058ba87d)

I understand the width,  that is a valid point, and I will work on it. I will also work on a toggle for the colors. 

The issue with the radio buttons seems limited to the browser you're using, so I need more information on that. What browser is it, what resolution is your monitor, what type of device are you on? Etc, the more information you can provide the better, thank you!

**Comment by DLCIncluded** [comment]
Fixed the width issue:
![image](https://github.com/user-attachments/assets/ed6d96f9-925c-49e4-a9e7-c32bb21f8be3)
![image](https://github.com/user-attachments/assets/c1424c3f-4c78-4b0b-81b6-cad59d194b00)

and added color as optional
![image](https://github.com/user-attachments/assets/f3112c7b-df9e-4402-9ad4-667c8a2e6a16)
![image](https://github.com/user-attachments/assets/70dea396-436d-41cb-afe1-d08dbd41aad5)

**Comment by DLCIncluded** [comment]
The content is centered using CSS FlexBox which is widely accepted on all major browsers ( [98.1% of desktop and  99.98% mobile](https://caniuse.com/flexbox))

I'd be happy to see if there is something I could do to fix it on the browser you're using, but it seems that its either a browser thats out of date, or does not follow industry standards. When you get time please let me know more about the device and browser and I'll see what, if anything, I can do

**Comment by bazyliquest** [comment]
yay, nice one with color switch :)
Width seems to be fine now on all devices I checked (mentioned below)

Radiobutton alignment:
It was Safari on iPadOS 18.0 (22A5350a) (iPad Mini). It's a beta, but Opera (5.0.6) on the same device behaves the same (but maybe they use Safari engine, idk). 
However desktop not-beta Safari 17.6 (19618.3.11.11.5) on MacOS Sonoma 14.6.1 (23G93) seems to have same problem (see attachment). Vivaldi on the same system renders boxes perfectly fine. 

So it seems to be Safari's problem.

https://github.com/user-attachments/assets/559afde4-724a-409f-8015-5d8010ef5e5c

**Comment by DLCIncluded** [comment]
Thanks for confirmation, unfortunately I can't support all browsers - and if Safari/Apple want to be special and do their own thing, theres not much I can do lol
